// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaIlP24y6V4OX--YGeBNRmz9E3i77gZsw',
    appId: '1:816999256331:web:fb8a4a9c658b287e9f120e',
    messagingSenderId: '816999256331',
    projectId: 'recordingstorage-58932',
    authDomain: 'recordingstorage-58932.firebaseapp.com',
    storageBucket: 'recordingstorage-58932.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1zAA4TXEAGjtW5SmyxxqB2aXLHgwQEI',
    appId: '1:816999256331:android:69c6676e0db1ea0a9f120e',
    messagingSenderId: '816999256331',
    projectId: 'recordingstorage-58932',
    storageBucket: 'recordingstorage-58932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtH39T2IBICoLE3nj5F4gduQoCqhNOISI',
    appId: '1:816999256331:ios:bf11ab46fd3ac3f89f120e',
    messagingSenderId: '816999256331',
    projectId: 'recordingstorage-58932',
    storageBucket: 'recordingstorage-58932.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtH39T2IBICoLE3nj5F4gduQoCqhNOISI',
    appId: '1:816999256331:ios:bf11ab46fd3ac3f89f120e',
    messagingSenderId: '816999256331',
    projectId: 'recordingstorage-58932',
    storageBucket: 'recordingstorage-58932.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaIlP24y6V4OX--YGeBNRmz9E3i77gZsw',
    appId: '1:816999256331:web:0726459ed394d6af9f120e',
    messagingSenderId: '816999256331',
    projectId: 'recordingstorage-58932',
    authDomain: 'recordingstorage-58932.firebaseapp.com',
    storageBucket: 'recordingstorage-58932.firebasestorage.app',
  );
}
